version: "3.3"
services:
  similar-products:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: similar-products
    ports:
      - 5000:5000
    volumes:
      - ./src/main/filters/filter-develop.properties:/app/filter-develop.properties
    environment:
      - SPRING_PROFILES_ACTIVE=develop
